### ISSUE TITLE
Add optional name to Vm's list

### ISSUE THREAD

**Issue by mihail-petrov** [ricofehr/nextdeploy#3]
Currently if you create a several **VM** from one project you are able to see only the **name** of the project no matter how many time you create it. This is very confusing, because the only way to distinguish between the different working instances is to write down there IP addresses. 

I am suggesting that the user is able to rename every single VM as he like. For example he could change the default project label with a custom label.

Thank you

**Comment by ricofehr** [comment]
Ok Done (commit ffdb0ab421d40bf0e787079fdaf59bb331af762f).
An optional "topic" field is added for vms. This field is filled with the branch name by default but can be override during vm launch or in "settings" popup on the vm line.
After that, this "topic" name appears in the second column of the vm list (instead of branch name currently).
