### ISSUE TITLE
Change repository branch from UI

### ISSUE THREAD

**Issue by mihail-petrov** [ricofehr/nextdeploy#4]
While working on a single virtual machine sometimes it is useful to have an ability to change the branches of the git repository associated with the Virtual machine. 

The already modified files should be stashed and the branch must be changed in order for the developer to make quickly see the changes that he made.

This feature will going to be useful for Project managers and Testers who does not have a direct access to the SSH of the virtual machine during the development of the project.

**Comment by ricofehr** [comment]
Already responded on this subject :)
I dont agree with that.

1/ Not the philosophy behind NextDeploy. If you need to change branch, you're working on an other topic, so => new vm. It's the concept of continuous development.

2/ And it's not just a "git checkout" process because there is all framework and project specific things: change database, assets to rebuild, lot of cache to clean, ... And sometimes, a different branch is an other project in many ways. So i mean, it will be a paint full task to implement that.

And anyway, if an user really want branch on his vm, he can already do that ... manually ! I let this possibility and i mean it's enough and a good compromise.
